sudo: required
dist: trusty

install:
  - sudo apt-get update
  - sudo apt-get install -y software-properties-common curl
  - sudo add-apt-repository -y ppa:webupd8team/java
  - sudo apt-get update
  - echo "oracle-java8-installer shared/accepted-oracle-license-v1-1 select true" | sudo debconf-set-selections
  - sudo apt-get install -y oracle-java8-installer
  - sudo echo "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
  - curl https://storage.googleapis.com/bazel-apt/doc/apt-key.pub.gpg | sudo apt-key add -
  - sudo apt-get update && sudo apt-get install -y bazel

script: bazel test tests:prometheus_test --test_verbose_timeout_warnings
